
#pragma once

#define START_LOOP 's'
#define REACTION_TIME_PRINT 'r' 
#define FINISHED 'f' 
#define COPY 'k'
#define END_PRINT 'e'
#define BREAK_LOOP 'b'
#define STIMULATION_MODE_BOTH 'b'
#define STIMULATION_MODE_VISUAL 'v'
#define STIMULATION_MODE_AUDITORY 'a'
#define ACTIVE_SENSOR 'l'

#define REACTION_TIME_MESSAGE_LENGTH 5
#define INSTRUCTION_MESSAGE_LENGTH 12
#define ACTIVE_SENSOR_MESSAGE_LENGTH 2